import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../../styles/Home.module.css'
import { NaverMap } from '../components/Tools/NaverMap/NaverMap'
import RenderAfterNaverMap from '../components/Tools/NaverMap/RenderAfterNaverMap'

export default function Home() {
  const [nMap, setNMap] = useState();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          strategy="beforeInterative"
          src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=83bfuniegk&amp;submodules=geocoder"
        ></script>
      </Head>
      <body>
        <RenderAfterNaverMap>
          <NaverMap
            mapDivId={"maps-getting-started-uncontrolled"} // default: react-naver-map
            style={{
              width: "100%",
              height: "100vh",
            }}
            defaultCenter={{ lat: 37.5665734, lng: 126.978179 }}
            defaultZoom={12}
            mapState={(map) => setNMap(map)}
          />
        </RenderAfterNaverMap>
      </body>
    </div>
  )
}

